version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: vue_app
    ports:
      - "5173:80"
    restart: always
