version: '3'

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    expose:
      - 8000
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: vue_app
    command: ["npm", "run", "build"]
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
